title: "Falcon Shuttle"
description: "Falcon LLC's Website"
baseurl: ""
url: "https://falcon-shuttle.github.io"

# site settings
taglong: +1 (435) 699-8482
tagshort: +1 (435) 699-8482

profile:
  cv: false

# author settings
author:
  phone: +1 (435) 699-8482
  name: Falcon LLC
photo: assets/files/Skiing-Falcon.png
background: assets/files/Mountains-Transparent.png

exclude:
  - demo/
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
